### ISSUE TITLE
Getting Runtime Exception when axe is analyzing for issues in selenium java

### ISSUE THREAD

**Issue by sachinArya** [dequelabs/axe-core-maven-html#137]
**Selenium** - 3.141.0

**Axe Maven dependency** 
        <dependency>
            <groupId>com.deque.html.axe-core</groupId>
            <artifactId>selenium</artifactId>
            <version>4.1.1</version>
        </dependency>
**Exception** - java.lang.RuntimeException: Unable to inject axe script

	at com.deque.html.axecore.selenium.AxeBuilder.analyzeRawContext(AxeBuilder.java:436)
	at com.deque.html.axecore.selenium.AxeBuilder.analyze(AxeBuilder.java:390)
	at com.automation.pom.AxeRun.runAxeReport(AxeRun.java:50)

**Comment by Zidious** [comment]
Closing due to inactivity. Please re-open if this is still apparent on 4.4.1
