### ISSUE TITLE
java.lang.RuntimeException: Error when enabling iframe communication

### ISSUE THREAD

**Issue by amandv** [dequelabs/axe-core-maven-html#170]
Getting below error while injecting axe-core script on page.

java.lang.RuntimeException: Error when enabling iframe communication
   [testng] 	at com.deque.html.axecore.selenium.AxeBuilder.analyzeRawContext(AxeBuilder.java:457)
   [testng] 	at com.deque.html.axecore.selenium.AxeBuilder.analyze(AxeBuilder.java:404)

**Comment by andrewedstrom** [comment]
This issue happens for us all the time and has caused our builds to become quite flakey on https://github.com/codeforamerica/shiba

**Comment by Zidious** [comment]
Closing due to inactivity, please re-open is issue is apparent in version: 4.4.1
