### ISSUE TITLE
BUG: AccessibilityScanRuntimeException on IOS safari

### ISSUE THREAD

**Issue by zcube123** [dequelabs/axe-core-maven-html#475]
**Describe the bug**
Error running Accessibility Scanning on IOS Safari. 

**Environment Happening In**
- [x] Production
- [ ] QA
- [ ] Dev

**To Reproduce**
1. Run AxeBuilder.analyze with a Remote web driver connected to a Safari browser.
3. Receive a null pointer exception:
`java.lang.NullPointerException: Cannot invoke "java.lang.Number.longValue()" because the return value of "java.util.Map.get(Object)" is null at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.getPageLoadTimeout(RemoteWebDriver.java:992) at com.deque.html.axecore.selenium.AxeBuilder.analyzeRawContext(AxeBuilder.java:655) at com.deque.html.axecore.selenium.AxeBuilder.analyze(AxeBuilder.java:613)`

**Expected behavior**
An iOS accessibility scan runs without error.

**Actual behavior**
A clear and concise description of what actually happened. 
Null pointer exception. 

**Screenshots**

**Related Tickets**
List out any user story or bug ticket(s) related to this bug. 

**Desktop (please complete the following information):**
- Product: [axe-core] 
- Product Version: 'com.deque.html.axe-core:selenium:4.9.+' (Latest)
- 'org.seleniumhq.selenium:selenium-java:4.16.1'
- Latest Product Version it is NOT happening in: Not sure.
- OS: macOS Ventura 13
 - Browser Safari
 - Browser Version 17

**Additional context**
Additional note, the error also happens on a more recent selenium api version. Version: 4.23.1

**Comment by Zidious** [comment]
Hey @zcube123,

Thanks for reporting this. Can you share more details about how your test is setup and if the page under test is public?
